version: "3.3"
services:

  consul:
    image: consul:1.9.1
    command: ["consul","agent","-config-file=/config/consul-config.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
      - "./consul_data:/data"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  hashicorpjapanapp:
    build:
      context: ./hashicorpjapanapp
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 8080:8080
      - 9102:9102
  hashicorpjapanapp_envoy:
    image: nicholasjackson/consul-envoy:v1.8.3-v1.13.4
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-hashicorpjapanapp.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "hashicorpjapanapp"]
    network_mode: "service:hashicorpjapanapp"

  hashiapp:
    build:
      context: ./hashiapp
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 1010:8080
  hashiapp_envoy:
    image: nicholasjackson/consul-envoy:v1.8.3-v1.13.4
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-hashiapp.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "hashiapp"]
    network_mode: "service:hashiapp"

  corpapp:
    build:
      context: ./corpapp
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - 2020:8080
  corpapp_envoy:
    image: nicholasjackson/consul-envoy:v1.8.3-v1.13.4
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-corpapp.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "corpapp"]
    network_mode: "service:corpapp"

  japanapp:
    build:
      context: ./japanapp
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - 3030:8080
  japanapp_envoy:
    image: nicholasjackson/consul-envoy:v1.8.3-v1.13.4
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-japanapp.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "japanapp"]
    network_mode: "service:japanapp"

  unintentionalapp:
    build:
      context: ./hashicorpjapanapp
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    ports:
      - 9090:8080
  unintentionalapp_envoy:
    image: nicholasjackson/consul-envoy:v1.8.3-v1.13.4
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/sidecar-unintentionalapp.json
    volumes:
      - "./consul.d:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "unintentionalapp"]
    network_mode: "service:unintentionalapp"

#  prometheus-server:
#    image: prom/prometheus
#    ports:
#      - 9999:9090
#    volumes:
#      - ./prometheus-envoy-intensions-demo.yml:/etc/prometheus/prometheus.yml
#    networks:
#      vpcbr:
#        ipv4_address: 10.5.0.9

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
