# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    origin_prometheus: prometheus01
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  - job_name: 'consul-metrics'
    metrics_path: /v1/agent/metrics
    scheme: http
    params:
      format: ['prometheus']
    scrape_interval: 10s
    scrape_timeout: 5s
    consul_sd_configs:
      - server: '10.5.0.2:8500'
        services:
          - consul
    relabel_configs:
      - source_labels: [__address__]
        separator:     ':'
        regex:         '(.*):(.*)'
        target_label:  '__address__'
        replacement:   '${1}:8500'
  - job_name: 'envoy-metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    consul_sd_configs:
      - server: '10.5.0.2:8500'
        services:
          - 'hashiapp'
          - 'corpapp'
          - 'japanapp'
          - 'hashicorpjapanapp'
    relabel_configs:
      - source_labels: [__address__]
        separator:     ':'
        regex:         '(.*):(.*)'
        target_label:  '__address__'
        replacement:   '${1}:9102'